### ISSUE TITLE
Migrate VME viewer under FigisMap OL3

### ISSUE THREAD

**Issue by eblondel** [openfigis/FigisMap#32]
The VME map viewer (except its factsheet component) is stilly relying on a separate FigisMap based on OL2. To investigate how to progressively move it under new FigisMap OL3. Vme viewer source code is located at: https://github.com/openfigis/vme-viewer
## FigisMap features
- [x] Double check environment/path variables for integration tests
- [x] Add VME layers to FigisMap OL3
- [x] Extend Layer Switcher currently in use (see #33)
- [x] Capacity to add context auto layers (as FigisMap params)
- [x] Investigate reason to have mapCenter / mapCenterProjection as FigisMap.defaults _Removed from FigisMap, specific to VME_
- [x] Isolate Time features into a FigisMap-time.js extension
- [x] Support of additional static labels #35
- [x] Extent Figis-Map-vector (previously 'cluster') to manage simple vector layers #36
- [x] Move support for GetFeatureInfo in FigisMap + FigisMap popup #34
- [x] Isolate wrapDateLine (center to Pacific) in FigisMap.ol.optimizeCenter function(+ add support more other projections)
### Projection Switcher
- [x] Projection is working well
- [x] Projection doesn't work between regional views 
- [x] Zoom level to refine
- [x] Fix issues with SPRFMO/NPFC (wrapDateLine)
### Layer Switcher #33
- [x] Layer groups enabled (VME layers, Additional features) (parametrized in FigisMap)
- [x] Groups are collapsable (parametrized in FigisMap)
- [x] Multiple baselayers enabled (parametrized in FigisMap)
- [x] Legend is hidden when layer is not visible (parametrized in FigisMap)
- [x] Layer ordering is improved to match current VME layer order (parametrized in FigisMap) 
- [x] VME layers bound to external toggle buttons 
### Reset
- [x] Reset is working well
### Time slider
- [x] Current year is displayed
- [x] Previous/Next are displayed well, Next hidden for current year
- [x] Time slider (layer filtering) is working well
### RFB Panel
- [x] Fetching RFB list
- [x] Selection of RFBs is Ok (Slight difference of map extent for NPFC/SPRFMO. For now it has been improved so SPRFMO zoom level set to 1 instead of 2)
- [x] Zoom level is accurate
- [x] Access to Info layer (Regional factsheet)
### Search
- [x] Free text search is operational 
- [x] Advanced search is operational
- [x] Search results
- [x] Search results / creation of highlight temporary vector layer
- [x] Search results / Get info (emulation of getFeatureInfo popup)
- [x] Search results / Zoom To Area
- [x] Search results / Access to VME factsheet
### Popup
- [x] Use of extended FigisMap-popup module with GetFeatureInfo (hence GeoExt dependency is removed, and popup is not using ExtJS) 
- [x] Popup general layout 
- [ ] Popup 'close' button layout
- [x] Popup dynamic position
- [x] Content display 
- [x] Functions / Access to Regional factsheet 
- [x] Functions / Access to VME factsheet
- [x] Functions / Download Shapefile 
- [x] Functions / Zoom to Area
### Embedded Link
- [x] Embedded Link encoder
- [x] Embedded Link decoder (with modification of visible auto layers)
- [x] Update of vme_e.html template & Verification of generated Iframe codes
- [x] Test Embedded Link with regional views and projections
## Other issues / feedback
- [ ] GFCM zooming in small devices is too much (GFCM area is cut) - Feedback from @fabio2111
