### ISSUE TITLE
Assess possible contributions to OpenLayers 3 / associated plugins

### ISSUE THREAD

**Issue by eblondel** [openfigis/FigisMap#37]
**Current OL3 API & plugins**
- [ ] Graticule improvements (contribution to OL3) **ONGOING** - See #18
- [ ] Popup control improvements ([ol3-popup](https://github.com/walkermatt/ol3-popup) plugin ) **ONGOING** - See https://github.com/walkermatt/ol3-popup/issues/17
- [ ] LayerSwitcher control improvements ([ol3-layerswitcher](https://github.com/walkermatt/ol3-layerswitcher) plugin) - See #33 

**New plugins**
- [x] LoadingPanel control (new plugin: https://github.com/eblondel/ol3-loadingpanel)
- [x] ZoomToMaxExtent control (new plugin: https://github.com/eblondel/ol3-zoomtomaxextent)
